spring.application.name=reservas-deportivas

spring.profiles.active=local

spring.jpa.open-in-view=false

spring.jackson.date-format=iso-8601
spring.jackson.serialization.write-dates-as-timestamps=false

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Springdoc OpenAPI / Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
